trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UseNode@1

- script: npm install -g tfx-cli

- task: PowerShell@2
  inputs:
    filePath: 'pack.ps1'

- task: SignPathSubmitSigningRequest@0
  inputs:
    waitForCompletion: 'sync'
    inputArtifactPath: 'SignPath.signpath-tasks-*.vsix'
    organizationId: '$(OrganizationId)'
    projectName: 'RnD-SP: SignPath Integrations AzureDevOps'
    signingPolicyName: 'test-signing'
    outputArtifactPath: '$(Build.ArtifactStagingDirectory)/SignPath.signpath-tasks.signed.vsix'
    allowOverwriting: false
    ciUserToken: '$(CIUserToken)'
    apiUrl: 'https://app.signpath.io/api/'
    waitForCompletionTimeoutInSeconds: '3600'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/SignPath.signpath-tasks.signed.vsix'
    artifact: 'SignPath.Integrations.AzureDevOps (signed vstx)'
