trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UseNode@1

- script: npm install -g tfx-cli

- task: PowerShell@2
  inputs:
    filePath: 'AzureDevOps/pack.ps1'
    arguments: '-MajorVersion $(MajorVersion) -MinorVersion $(MinorVersion) -PatchVersion $(PatchVersion)'
    workingDirectory: 'AzureDevOps/'

- task: SignPathSubmitSigningRequest@0
  inputs:
    waitForCompletion: 'sync'
    inputArtifactPath: 'AzureDevOps/SignPath.signpath-tasks-*.vsix'
    organizationId: '$(OrganizationId)'
    projectName: 'RnD-SP: SignPath Integrations AzureDevOps'
    signingPolicyName: 'test-signing'
    outputArtifactPath: 'AzureDevOps/SignPath.signpath-tasks-signed.vsix'
    allowOverwriting: false
    ciUserToken: '$(CIUserToken)'
    apiUrl: 'https://app.signpath.io/api/'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)AzureDevOps/SignPath.signpath-tasks-signed.vsix'
    artifact: 'SignPath.Integrations.AzureDevOps (signed vstx)'
